config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "guide", to: "toppages#show"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"

  resources :users, only: [:show, :new, :create] do
    member do
      get :likes
    end
  end


  resources :reviews, only: [:show, :create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  
  validates :kind, presence: true
  validates :point, presence: true
  validates :product_name, length: { maximum: 50 }
  validates :comment, presence:true, length: { maximum: 255 }
  
  has_many :likes, dependent: :destroy
  has_many :likes_reviews, through: :likes, source: :user
  
  enum kind: {
    さつまいも:"さつまいも",干し芋:"干し芋"
  }
  
  enum point: {
    ５点:5,４点:4,３点:3,２点:2,１点:1
  }

  enum producing_area: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
    不明（国内）:48,不明（国外）:49
  }
  
  validates :point,
            inclusion: { in: Review.points.keys }
  validates :producing_area,
            inclusion: { in: Review.producing_areas.keys }
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :profile, length: { maximum: 200 }
  has_secure_password
  
  has_many :reviews
  has_many :likes, dependent: :destroy
  has_many :likes_reviews, through: :likes, source: :review
  
  def like(review)
      self.likes.find_or_create_by(review_id: review.id)
  end
  
  def unlike(review)
    like = self.likes.find_by(review_id: review.id)
    like.destroy if like
  end
  
  def liking?(review)
    self.likes_reviews.include?(review)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_reviews = user.reviews.count
    @count_likes_reviews = user.likes_reviews.count
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    review = Review.find(params[:review_id])
    current_user.like(review)
    flash[:success] = "イモ惚れボタンを押しました"
    redirect_to likes_user_path(current_user)
  end
  
  def destroy
    review = Review.find(params[:review_id])
    current_user.unlike(review)
    flash[:success] = "イモ惚れボタンを解除しました"
    redirect_to likes_user_path(current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def show
    @review = Review.find(params[:id])
  end
  
  def create
    @review =current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = "クチコミを投稿しました"
      redirect_to root_url
    else
      @reviews = Review.order("created_at DESC").page(params[:page])
      flash.now[:danger] = "クチコミの投稿ができませんでした"
      render "toppages/index"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = "クチコミを削除しました"
    redirect_to root_url
  end
  
  private
  
  def review_params
    params.require(:review).permit(:kind, :point, :product_name, :producing_area, :comment)
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインしました"
      redirect_to @user
    else
      flash.now[:danger] = "ログインできませんでした"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController

  def index
    @reviews_1 = Review.limit(3).order("created_at DESC")

    if logged_in?
      @review = current_user.reviews.build
      @reviews = Review.order("created_at DESC").page(params[:page]).per(5)
      counts(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :likes]
  def index
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order("created_at DESC").page(params[:page]).per(5)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "会員登録が完了しました！"
      redirect_to @user
    else
      flash.now[:danger] = "会員登録に失敗しました"
      render :new
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @reviews = @user.likes_reviews.page(params[:page]).per(5)
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning" >
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center">
    <h6><%= link_to "|ガイドライン|", guide_path, :target => ["_blank"] %></h6>
    <h6>© 2019 おいも村 oimomura.</h6>
  </div>
</footer>

<!-- 
<header>
  <nav class="navbar_foot navbar-default navbar-fixed-bottom">
    <div class="container">
      <h6 class="nav navbar-text navbar-right">© 2019 おいも村 oimomura</h6>
     </div>
  </nav>
</header>
-->

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="/images/logo.png" alt="oimomura"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="nav_btn"><%= link_to "マイページ", user_path(current_user), class: "btn" %></li>
            <li class="nav_btn"><%= link_to "ログアウト", logout_path, class: "btn", method: :delete %></li>
          <% else %>
            <li class="nav_btn"><%= link_to "会員登録", signup_path, class: "btn" %></li>
            <li class="nav_btn"><%= link_to "ログイン", login_path, class: "btn" %></li>
          <% end %>
        </ul>
      </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>おいも村 -Oimomura-</title>
    <%= csrf_meta_tags %>
    
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets-->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    
    <!-- app/assets/javascripts-->
    <%= javascript_include_tag "application", "data-turbolinks-truck": "reload" %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  
  <body>
    <%= render "layouts/navbar" %>

    <div class="wrapper">
      
      <div class="container">
        <%= render "layouts/flash_messages" %>
    
        <%= yield %>
      </div>
    </div>
    
    <div class="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/likes/_likes_button.html.erb
<% if current_user.liking?(review) %>
  <%= form_for(current_user.likes.find_by(review_id: review.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :review_id, review.id %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"><%= f.submit "イモ惚れ（お気に入り）を外す", class: "btn btn-default btn-xs" %></span>
  <% end %>
<% else %>
  <%= form_for(current_user.likes.build) do |f| %>
    <%= hidden_field_tag :review_id, review.id %>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"><%= f.submit "イモ惚れ（お気に入り）する", class: "btn btn-danger btn-xs" %></span>
  <% end %>
<% end %>

app/views/reviews/_reviews.html.erb
<div class="reviews_box">
  <div class="media-list">
    <% reviews.each do |review| %>
      <div class="media">
          <div>
            <%= link_to review.user.name, user_path(review.user) %> <span class="text-muted">さんのクチコミ</span>
          </div>
        <div class="media-left">
          <img class="review_img" src="/images/icon_1.png">
        </div>
        <div class="media-body">
          <div>
            <span class="delete_review_button">
          <% if current_user == review.user %>
            <%= link_to "削除", review, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-xs" %>
          <% end %>
            </span>
            <p>
              <span class="reviews_menu">種類</span> <%= review.kind %>
              <span class="reviews_menu">産地</span> <%= review.producing_area %>
              <span class="reviews_menu">点数</span> <%= review.point %>
            </p>
            <p><span class="reviews_menu">商品名</span> <%= review.product_name %></p>
            <p><span class="reviews_menu">コメント</span></p>
            <p><%= review.comment.truncate(40) %></p>
            <span class="read_more">
              <%= link_to "詳細", review_path(review), class: "btn btn-dafault btn-xs" %>
            </span>
          </div>
        </div>
      </div>
        <div class="text-right">
            <h6 class="media-heading"><%= review.user.created_at %></h6>

          <% unless current_user == review.user %>
            <%= render "likes/likes_button", review: review %>
          <% end %>
        </div>
      <% end %>
    <%= paginate reviews %>
  </div>
</div>

app/views/reviews/_reviews_sample.html.erb
<div class="sample_reviews_box">
  <div class="media-list">
    <% @reviews_1.each do |review| %>
      <div class="media">
          <div>
            <%= review.user.name %> <span class="text-muted">さんからのクチコミ</span>
          </div>
        <div class="media-left">
          <img class="review_img" src="/images/icon_1.png">
        </div>
        <div class="media-body">
          <p>
            <span class="reviews_menu">種類</span> <%= review.kind %>
            <span class="reviews_menu">産地</span> <%= review.producing_area %>
            <span class="reviews_menu">点数</span> <%= review.point %>
          </p>
          <p>
            <span class="reviews_menu">商品名</span> <%= review.product_name %>
          </p>
          <p>
            <span class="reviews_menu">コメント</span>
          </p>
          <p>
            <%= review.comment.truncate(40) %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="reviews_box col-md-6 col-md-offset-3">
  <div class="media-list">
    <div class="media">
      <div>
        <%= link_to @review.user.name, user_path(@review.user) %> <span class="text-muted">さんのクチコミ</span>
      </div>
      <div class="media-left">
        <img class="review_img" src="/images/icon_1.png">
      </div>
      <div class="media-body">
        <div>
          <span class="delete_review_button">
            <% if current_user == @review.user %>
              <%= link_to "削除", @review, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-xs" %>
            <% end %>
          </span>
          <p>
            <span class="reviews_menu">種類</span> <%= @review.kind %>
            <span class="reviews_menu">産地</span> <%= @review.producing_area %>
            <span class="reviews_menu">点数</span> <%= @review.point %>
          </p>
          <p><span class="reviews_menu">商品名</span> <%= @review.product_name %></p>
          <p><span class="reviews_menu">コメント</span></p>
          <p><%= @review.comment %></p>
        </div>
      </div>
    </div>
    <div class="text-right">
      <h6 class="media-heading"><%= @review.user.created_at %></h6>
    </div>
    <div>
      <% unless current_user == @review.user %>
        <%= render "likes/likes_button", review: @review %>
      <% end %>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "戻る", user_path(current_user), class: "btn btn-default btn-md" %>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <div class="col-md-12 text-center" >
        <img class="user_profile_img" src="/images/icon_2.png">
        <p><%= current_user.name %></p>
      </div>
      <div class="status-box">
        <%= render "users/status" %>
      </div>
      <div>
        <%= form_for(@review) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>

          <div class="form-group">
            <%= f.label :kind, "種類 *" %>
            <%= f.select :kind, Review.kinds.keys, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :point, "点数 *" %>
            <%= f.select :point, Review.points.keys, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :producing_area, "産地" %>
            <%= f.select :producing_area, Review.producing_areas.keys, class: "form-control"%>
          </div>

          <div class="form-group">
            <%= f.label :product_name, "商品名" %>
            <%= f.text_area :product_name, class: "form-control", rows: 1 %>
          </div>
          
          <div class="form-group">
            <%= f.label :comment, "コメント *" %>
            <%= f.text_area :comment, class: "form-control", rows: 4 %>
          </div>
          
          <%= f.submit "クチコミ投稿", class: "btn btn-default btn-block" %>
        <% end %>
      </div>
    </aside>
    <div class="col-xs-12 col-md-6 col-md-offset-1">
      <h3 class="text-center">みんなのクチコミ</h3>
      <%= render "reviews/reviews", reviews: @reviews %>
    </div>
  </div>
<% else %>
<div class="conteiner">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="info col-md-12 text-center" >
        <img class="info_1" src="/images/imochan_lg.png"><img class="info_2" src="/images/fukidashi2.png">
      </div>
    </div>
  </div>

  <div class="center jumbotron">
    <div class="text-center">
      <h1>おいも村でできることって？？</h1>
      <ul>
        <li><h3>クチコミがかけるよ！</h3></li>
        <li><h3>みんなのクチコミがみられるよ！</h3></li>
        <li><h3>クチコミをお気に入りに登録することができるよ！</h3></li>
      </ul>
    </div>
    <div class="signup_button text-center">
      <%= link_to "さっそく会員登録してみよう", signup_path, class: "btn btn-warning" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <div class="sample-reviews-title">
        <h3>みんなのクチコミを見てみよう！</h3>
      </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <div class="post-sample-body">
        <%= render "reviews/reviews_sample", reviews: @reviews %>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/toppages/show.html.erb
<div class="user_new text-center">
    <h2>本サイトについて</h2>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div>
      <h4>はじめに</h4>
      <p>おいも村のクチコミは、さつまいも好きの皆様による主観的な感想や評価をインターネット上に公開することで、おいもや干し芋選びの参考として多くの皆様に活用いただくことを目的としています。</p>
      <p>クチコミサイトであるおいも村には、忌憚ないクチコミをお寄せいただきたいと考えておりますが、健全なコミュニティサイト運営を行うため、クチコミを投稿する際に遵守いただく事項につき本ガイドラインを規定させていただきます。</p>
      <p>会員の皆様には、本ガイドラインの遵守にご協力いただきますよう、よろしくお願いいたします。</p>
      <p>以下、ガイドラインの詳細となります。会員登録を行う前に必ずお読みください。</p>
    </div>
  </div>
  <div class="col-md-8 col-md-offset-2">
    <div>
      <h4>1.クチコミは実際に召し上がった評価を中心に書いて下さい｡</h4>
    </div>
    <div>
      <h4>2.次の内容のクチコミの掲載はお断りしております。</h4>
      <ul>
        <li>販売店や商品等へ悪影響を及ぼすかつ内容の確認が困難な事象についての投稿</li>
        <li>衛生管理面のクレーム</li>
        <li>販売店等の法律違反・契約違反に関する内容</li>
        <li>個人に対しての誹謗中傷、販売店・商品等への断定的批判、及び不適切な表現</li>
        <li>販売店・商品等への個人的なクレームやトラブルに関する内容</li>
        <li>トラブルがあった販売店・商品等へのクチコミ</li>
        <li>法令に反する行為や犯罪行為等に結びつくクチコミ</li>
        <li>プライバシーを侵害するもの</li>
        <li>著作権等の知的財産権を侵害するもの（判断は会員様ご自身で判断いただくことになり、本サイトは一切責任を負いません）</li>
        <li>対価を目的としたもの</li>
        <li>販売店・製造者自身による、主観的ではないクチコミ（自作自演など）</li>
      </ul>
    </div>
    <div>
      <h4>3.投稿されたすべてのクチコミは、運営側の判断により修正・加筆・削除等することがあります。</h4>
    </div>
    <div>
      <h4>4.投稿されたすべてのクチコミは、当サイトに利用許諾されることになります。</h4>
    </div>
    <div>
      <h4>5.クチコミの著作権は当サイトに属します。</h4>
    </div>
    <div>
      <h4>6.サイトに対して妨害行為等を行っている方に関して、法的措置を取らせていただく場合があります。</h4>
    </div>
    <div>
      <h4>7.ガイドラインは予告なしに変更、修正、 追加、削除させていただくことがあります。</h4>
    </div>
    <div>
      <h4>8.当サイトは予告なしに変更、修正、追加、削除させていただくことがあります。</h4>
    </div>
      <form class="text-center"><input type="button" value="閉じる" onClick="window.open('','_self').close();"></form>
  </div>
</div>

app/views/users/_status.html.erb
<div class="row">
  <div class="status">
    <table class="text-center col-xs-10 col-xs-offset-1">
    <tr>
      <th class="text-center">クチコミ</th>
      <th class="text-center">イモ惚れ</th></th>
    </tr>
    <tr>
      <td><%= @count_reviews %></td>
      <td><%= @count_likes_reviews %></td>
    </tr>
    </table>
  </div>
</div>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body text-center">
        <img class="user_profile_img" src="/images/icon_2.png">
      </div>
    </div>
    <%= render "status" %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= "active" if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>自分のクチコミ <span class="badge"><%= @count_reviews %></span><% end %></li>
      <li class="<%= "active" if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>イモ惚れ！ <span class="badge"><%= @count_likes_reviews %></span><% end %></li>
    </ul>
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <%= render "reviews/reviews", reviews: @reviews %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="user_new text-center">
    <h2><img src="/images/icon_2.png">会員登録</h2>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, "ニックネーム" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "メールアドレス"%>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      
      <div class="form*group">
        <%= f.label :password_confirmation, "パスワード(確認)" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      
      <div class="guide text-center">
        <h6>登録ボタンを押す前に<%= link_to "こちらのガイドライン", guide_path, :target => ["_blank"] %>を必ずお読みください</h6>
        <h6>ご登録いただいた時点でガイドライン了承済みと判断させていただきます</h6>
      </div>
      
      <div class="text-center">
      <%= f.submit "会員登録(無料)", class: "btn btn-warning btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body text-center">
        <img class="user_profile_img" src="/images/icon_2.png">
      </div>
    </div>
    <%= render "status" %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><a href="#">自分のクチコミ</a></li>
      <li><a href="#">イモ惚れ！</a></li>
    </ul>
  </div>
</div>